---
- name: Assure Docker running
  service: name=docker state=started

- name: Enable Docker at boot
  service: name=docker enabled=yes

- name: install docker-py
  pip: name=docker-py state=present
